class_names = ['burgers',
               'chicken biriyani',
               'chicken pakoda',
               'chicken roll',
               'chicken tandori',
               'chiken curry',
               'chole bhature ',
               'dal fry',
               'dosa',
               'egg curry',
               'fish curry',
               'noodles',
               'paneer curry',
               'pizza',
               'prawn curry',
               'rice',
               'samosa',
               'vada pav']
